feat(apps): create endpoint api

diff --git a/githooks/pre-commit b/githooks/pre-commit
--- a/githooks/pre-commit
+++ b/githooks/pre-commit
@@ -1,14 +1,25 @@
-GO_FILES=$(git diff --cached --name-only --diff-filter=ACMR | grep '.go$')
+#!/usr/bin/env bash
 
-if [ -n "$GO_FILES" ]; then
-    for FILE in $GO_FILES; do
-        $(go env GOPATH)/bin/golangci-lint run $FILE
-        if [[ $? != 0 ]]; then
-            printf "Commit failed! Please fix errors before committing.\n"
-            exit 1
-        fi
-    done
-   git add $GO_FILES
+staged_files=$(git diff --diff-filter=d --cached --name-only | grep -E '\.(go)$')
 
-   echo "Go code formatting applied successfully."
+echo "run golangci-lint..."
+
+fail=0
+msg=""
+
+for file in $staged_files
+do
+  echo "checking $file"
+  golangci-lint run --fix "$file" --disable typecheck
+  if [ $? -ne 0 ]; then
+    (( fail++ ))
+  fi
+done
+
+if [ $fail -gt 0 ]
+then
+  echo "$fail linter errors found, please fix it before commiting again."
+  exit 1  
 fi
+
+echo "no linter error found, commiting..."
